version: '3.8'

services:
  ever-blog:
    image: ever-blog:0.0.1
    build:
      context: .
      dockerfile: dockerfile
      platforms:
        - linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
